# Generated by Django 4.1.7 on 2023-03-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_attribute1_category_attribute1_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
