# Generated by Django 4.1.7 on 2023-04-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_attribute1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='autofocus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery_life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='build_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cooling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_efficiency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sound_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_quality',
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='products.AttributeValue', to='products.attribute'),
        ),
    ]
