# Generated by Django 4.1.7 on 2023-04-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_attribute_remove_product_autofocus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeValue',
            new_name='ProductAttribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compatibility',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='smart_features',
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
    ]
