# Generated by Django 4.1.7 on 2023-04-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='subattribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subattribute'),
        ),
    ]
