# Generated by Django 4.1.7 on 2023-04-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productattribute_subattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='subattribute',
        ),
    ]
