# Generated by Django 4.1.7 on 2023-04-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productattribute_subattribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='subattribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.subattribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subattribute',
            name='value',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute', 'subattribute')},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
    ]
