# Generated by Django 4.1.7 on 2023-04-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='subattribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subattribute'),
        ),
    ]
